import type { Metadata } from 'next';
import { Roboto, Lato } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/layouts/Header';

const roboto = Roboto({
  variable: '--primaryfont',
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});

const SF_Pro = localFont({
  src: [
    {
      path: '../fonts/SFPRODISPLAYTHINITALIC.otf',
      weight: '100',
      style: 'italic',
    },
    {
      path: '../fonts/SFPRODISPLAYULTRALIGHTITALIC.otf',
      weight: '200',
      style: 'italic',
    },
    {
      path: '../fonts/SFPRODISPLAYLIGHTITALIC.otf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../fonts/SFPRODISPLAYREGULAR.otf',
      weight: '400',
      style: 'normal',
    },
    { path: '../fonts/SFPRODISPLAYMEDIUM.otf', weight: '500', style: 'normal' },
    {
      path: '../fonts/SFPRODISPLAYSEMIBOLDITALIC.otf',
      weight: '600',
      style: 'italic',
    },
    { path: '../fonts/SFPRODISPLAYBOLD.otf', weight: '700', style: 'normal' },
    {
      path: '../fonts/SFPRODISPLAYHEAVYITALIC.otf',
      weight: '800',
      style: 'italic',
    },
    {
      path: '../fonts/SFPRODISPLAYBLACKITALIC.otf',
      weight: '900',
      style: 'italic',
    },
  ],
  variable: '--secondaryfont',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${SF_Pro.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
